version: "3.8"

services:
  webserver:
    build:
      context: docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./www:/www
  php:
    build:
      context: docker/php
    container_name: php
    restart: always
    networks:
      - internal
    depends_on:
      - db
    volumes:
      - ./www:/www

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_ROOT_PASSWORD: mysql_root_password
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
    - internal
networks:
  internal:
    driver: bridge